name: Build and deploy Vite React app to Azure Web App - mohamed

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js (Vite requires Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Use the version required by your project

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the Vite project
      - name: Build Vite project
        run: npm run build

      # Upload the build folder as an artifact for the deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: vite-app
          path: ./build  # The default output folder for Vite build is 'dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Download the build artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: vite-app

      # Login to Azure using GitHub Secrets
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EB2BAB81A8BA4165AB12D7A5F401B5FF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_769D031D87F446D5B741A8759A61A925 }}
          subscription-id: ${{ secrets. }}AZUREAPPSERVICE_SUBSCRIPTIONID_231E956D0B7B443C9964A42DA043798D

      # Deploy the build artifact to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mohamed'  # Replace with your Azure Web App name
          slot-name: 'Production'
          package: './build'  # The folder containing the built Vite app
